#!/usr/bin/env python3
"""Regenerate data/bundle.js from the batch JSON files.

The app fetches data/batch-NN.json when it is served over http(s). Browsers
refuse to fetch local files when index.html is opened straight from disk
(file://), so the same batches are also written to data/bundle.js, which a
plain <script> tag is allowed to load from disk. The JSON files stay the
single source of truth — this script only mirrors them.

Run it after adding or editing a batch, from anywhere:

    python3 top2000/tools/bundle_batches.py
"""

import json
import pathlib
import sys

DATA_DIR = pathlib.Path(__file__).resolve().parent.parent / "data"
OUT = DATA_DIR / "bundle.js"

HEADER = """/* Generated by tools/bundle_batches.py — do not edit by hand.

   A copy of data/batch-*.json for opening index.html straight from disk, where
   browsers block fetch() of local files. Re-run the script after changing a
   batch. */

window.T2K_BUNDLE = """


def main() -> int:
    files = sorted(DATA_DIR.glob("batch-*.json"))
    if not files:
        print(f"No batch-*.json files in {DATA_DIR}", file=sys.stderr)
        return 1

    bundle = {}
    for path in files:
        with path.open(encoding="utf-8") as fh:
            batch = json.load(fh)
        number = batch.get("batch")
        if not isinstance(number, int):
            print(f"{path.name}: missing an integer \"batch\" field", file=sys.stderr)
            return 1
        if number in bundle:
            print(f"{path.name}: batch {number} is already defined", file=sys.stderr)
            return 1
        bundle[number] = batch

    body = json.dumps(
        {str(n): bundle[n] for n in sorted(bundle)},
        ensure_ascii=False,
        indent=2,
    )
    OUT.write_text(HEADER + body + ";\n", encoding="utf-8")

    words = sum(len(b.get("words", [])) for b in bundle.values())
    print(f"Wrote {OUT.relative_to(DATA_DIR.parent)} — {len(bundle)} batch(es), {words} words.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
